# Generated by Django 5.1.4 on 2024-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('packet_type', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('device_type', models.IntegerField()),
                ('device_latitude', models.FloatField()),
                ('device_longitude', models.FloatField()),
                ('device_altitude', models.FloatField()),
            ],
        ),
    ]
